/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mccormack;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.assertj.core.api.Assertions.assertThat;


@SpringBootTest
class PrimeRangesAPITest {
    @Test
    void appHasAGreeting() {
        assertThat(true).isTrue();
    }
}
